apiVersion: v1
kind: Service
metadata:
  name: microblog-service
  labels:
    app: microblog
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: microblog
