version: '3.8'

services:
  backend:
    build:
      context: ./infra/docker
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    build:
      context: ./infra/docker
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microblog
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: